/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.panel;

import db.connection.PersonnelDAO;
import entities.CompanyDetails;
import entities.FileTypeFilter;
import gui.frames.Main;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JSeparator;
import worker.Dialog;
import worker.Message;

/**
 *
 * @author HUNGUYEN
 */
public class PanelCompany extends javax.swing.JPanel {

    private Main main;
    private JPopupMenu picPopupMenu;
    private byte[] logo;

    public byte[] getLogo() {
        return logo;
    }

    public void setLogo(byte[] logo) {
        this.logo = logo;
    }

    /**
     * Creates new form Company
     */
    public PanelCompany(Main main) {
        initComponents();
        this.main = main;
        setPopupMenu(lbCompLogo);
    }

    public PanelCompany(CompanyDetails com) {
        initComponents();
        loadInfo(com);
        btSave.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfCompNameVN = new javax.swing.JTextField();
        tfCompNameEN = new javax.swing.JTextField();
        tfCompManager = new javax.swing.JTextField();
        tfCompFax = new javax.swing.JTextField();
        tfCompAddressVN = new javax.swing.JTextField();
        tfCompAddressEN = new javax.swing.JTextField();
        tfCompTaxCode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfCompPhone = new javax.swing.JTextField();
        tfCompBankID = new javax.swing.JTextField();
        lbCompLogo = new javax.swing.JLabel();
        btSave = new javax.swing.JButton();
        dcCompRegistDay = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        tfCompShortName = new javax.swing.JTextField();

        jLabel1.setText("Tên công ty (VN):");

        jLabel2.setText("Tên công ty (EN):");

        jLabel3.setText("Tên giám đốc:");

        jLabel4.setText("Số Fax:");

        jLabel5.setText("Địa chỉ (VN):");

        jLabel6.setText("Địa chỉ (EN):");

        jLabel7.setText("Mã số thuế: ");

        jLabel8.setText("Số điện thoại:");

        jLabel9.setText("Số tài khoản:");

        jLabel10.setText("Ngày đăng ký:");

        lbCompLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCompLogo.setText("Logo Công ty");
        lbCompLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbCompLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbCompLogo.setMaximumSize(new java.awt.Dimension(150, 200));
        lbCompLogo.setMinimumSize(new java.awt.Dimension(150, 200));
        lbCompLogo.setPreferredSize(new java.awt.Dimension(150, 200));

        btSave.setText("Lưu thông tin");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        dcCompRegistDay.setDateFormatString("dd - MM - yyyy");

        jLabel11.setText("Tên viết tắt: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCompNameVN, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCompNameEN, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tfCompShortName, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfCompTaxCode, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcCompRegistDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfCompAddressVN, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCompAddressEN, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfCompManager, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCompPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfCompFax, javax.swing.GroupLayout.DEFAULT_SIZE, 6, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCompBankID, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCompLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSave)
                .addGap(206, 206, 206))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel11, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfCompFax, tfCompManager, tfCompTaxCode});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel8, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dcCompRegistDay, tfCompBankID});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfCompNameEN, tfCompNameVN, tfCompShortName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCompLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfCompNameVN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfCompNameEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tfCompShortName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfCompManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(tfCompPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfCompFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(tfCompBankID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfCompAddressVN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tfCompAddressEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcCompRegistDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(tfCompTaxCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)))
                        .addGap(18, 18, 18)
                        .addComponent(btSave)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        PersonnelDAO pDAO = new PersonnelDAO();
        CompanyDetails com = new CompanyDetails();
        boolean check = true;
        com.setTenCtyVN(tfCompNameVN.getText());
        com.setTenCtyEN(tfCompNameEN.getText());
        com.setTenVietTat(tfCompShortName.getText());
        com.setTenGiamDoc(tfCompManager.getText());
        com.setSoDienThoai(tfCompPhone.getText());
        com.setSoFax(tfCompFax.getText());
        com.setSoTaiKhoan(tfCompBankID.getText());
        com.setDiaChiVN(tfCompAddressVN.getText());
        com.setDiaChiEN(tfCompAddressEN.getText());
        com.setMaSoThue(tfCompTaxCode.getText());
        if (dcCompRegistDay.getDate() == null) {
            Dialog.showMsg("Ngày thành lập" + Message.DATE, 0);
            check = false;
        } else {
            com.setNgayDangKy(new Date(dcCompRegistDay.getDate().getTime()));
        }
        com.setLogo(this.logo);
        if (check) {
            if (pDAO.insertCompanyDetails(com)) {
                JOptionPane.showMessageDialog(null, "Đã thiết lập thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                this.main.setTree(com.getTenCtyVN());
                this.main.getTpRight().remove(this);
            }
        }
    }//GEN-LAST:event_btSaveActionPerformed

    private void setPopupMenu(JLabel lbPicture) {
        picPopupMenu = new JPopupMenu();
        JMenuItem miLoad = new JMenuItem("Load");
        JSeparator separator = new JSeparator();
        JMenuItem miDelete = new JMenuItem("Delete");

        miLoad.addActionListener((ActionEvent e) -> {
            showFileChooser();
        });

        miDelete.addActionListener((ActionEvent e) -> {
            delPic();
        });

        picPopupMenu.add(miLoad);
        picPopupMenu.add(separator);
        picPopupMenu.add(miDelete);

        lbPicture.setComponentPopupMenu(picPopupMenu);
    }

    private void delPic() {
        lbCompLogo.setIcon(null);
        lbCompLogo.setText("Ảnh cá nhân");
    }

    private void showFileChooser() {
        JFileChooser fileChooser = new JFileChooser();
        int result;
        fileChooser.setDialogTitle("Chọn một ảnh nhân viên");
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.setFileFilter(new FileTypeFilter(".png", "PNG"));
        fileChooser.setFileFilter(new FileTypeFilter(".gif", "GIF"));
        fileChooser.setFileFilter(new FileTypeFilter(".jpg", "JPG"));
        result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                File selectedFile = fileChooser.getSelectedFile();
                BufferedImage img = ImageIO.read(selectedFile);
                Image img1 = img.getScaledInstance(150, 200, Image.SCALE_SMOOTH);
                ImageIcon imgi = new ImageIcon(img1);
                lbCompLogo.setText("");
                lbCompLogo.setIcon(imgi);
                convertImage(selectedFile.getAbsolutePath());
            } catch (IOException ex) {
                Logger.getLogger(PanelInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSave;
    private com.toedter.calendar.JDateChooser dcCompRegistDay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbCompLogo;
    private javax.swing.JTextField tfCompAddressEN;
    private javax.swing.JTextField tfCompAddressVN;
    private javax.swing.JTextField tfCompBankID;
    private javax.swing.JTextField tfCompFax;
    private javax.swing.JTextField tfCompManager;
    private javax.swing.JTextField tfCompNameEN;
    private javax.swing.JTextField tfCompNameVN;
    private javax.swing.JTextField tfCompPhone;
    private javax.swing.JTextField tfCompShortName;
    private javax.swing.JTextField tfCompTaxCode;
    // End of variables declaration//GEN-END:variables

    private void convertImage(String absolutePath) {
        File imageFile = new File(absolutePath);
        FileInputStream fis;
        setLogo(new byte[(int) imageFile.length()]);
        try {
            fis = new FileInputStream(imageFile);
            fis.read(this.logo);
            fis.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PanelInfo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PanelInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadInfo(CompanyDetails com) {

        tfCompNameVN.setText(com.getTenCtyVN());
        tfCompNameEN.setText(com.getTenCtyEN());
        tfCompAddressEN.setText(com.getDiaChiEN());
        tfCompAddressVN.setText(com.getDiaChiVN());
        tfCompBankID.setText(com.getSoTaiKhoan());
        tfCompFax.setText(com.getSoFax());
        tfCompManager.setText(com.getTenGiamDoc());
        tfCompPhone.setText(com.getSoDienThoai());
        tfCompShortName.setText(com.getTenVietTat());
        tfCompTaxCode.setText(com.getMaSoThue());
        dcCompRegistDay.setDate(com.getNgayDangKy());

        tfCompNameVN.setEditable(false);
        tfCompNameEN.setEditable(false);
        tfCompAddressEN.setEditable(false);
        tfCompAddressVN.setEditable(false);
        tfCompBankID.setEditable(false);
        tfCompFax.setEditable(false);
        tfCompManager.setEditable(false);
        tfCompPhone.setEditable(false);
        tfCompShortName.setEditable(false);
        tfCompTaxCode.setEditable(false);
        dcCompRegistDay.setEnabled(false);
        if (com.getLogo() != null) {
            ImageIcon img = new ImageIcon(com.getLogo());
            Image img1 = img.getImage().getScaledInstance(150, 200, Image.SCALE_SMOOTH);
            lbCompLogo.setText("");
            lbCompLogo.setIcon(new ImageIcon(img1));
        } else {
            delPic();
        }
    }
}
