/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.panel;

import db.connection.OfficeDAO;
import java.util.ArrayList;
import entities.Office;
import entities.PersonnelTreeModel;
import java.awt.event.ActionEvent;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTree;
import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author HUNGUYEN
 */
public class TreePanel extends javax.swing.JPanel {

    /**
     * Creates new form TreePanel
     */
    
    private OfficeDAO oDAO = new OfficeDAO();
    
    public TreePanel(String name) {
        initComponents();
        loadTree(name);
        setPopupMenu(personnelTree, name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        personnelTree = new javax.swing.JTree();

        setMinimumSize(new java.awt.Dimension(200, 100));

        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 100));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Công ty ABC");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Phòng Kế Toán");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Nhân viên A");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Phòng Nhân Sự");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Nhân viên B");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        personnelTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        personnelTree.setLargeModel(true);
        personnelTree.setMinimumSize(new java.awt.Dimension(200, 100));
        jScrollPane1.setViewportView(personnelTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree personnelTree;
    // End of variables declaration//GEN-END:variables

    private void loadTree(String name) {
        ArrayList<Office> oList = oDAO.getOfficeList();
        personnelTree.setModel(PersonnelTreeModel.buildTreeModel(name, oList));
        PersonnelTreeModel.setPersonnelTree(personnelTree);
        personnelTree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
    }

    private void setPopupMenu(JTree personnelTree, String name) {
        JPopupMenu popup = new JPopupMenu();
        
        JMenuItem miReload = new JMenuItem("Tải lại danh sách cây");
        miReload.addActionListener((ActionEvent e) -> {
            loadTree(name);
        });
        popup.add(miReload);
        
        personnelTree.setComponentPopupMenu(popup);
    }
}
